//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OrderedFoodDetails
    {
        public int id { get; set; }
        public Nullable<int> fk_OrderId { get; set; }
        public Nullable<int> fk_DishId { get; set; }
        public Nullable<int> DishQuantity { get; set; }
    
        public virtual tbl_Dishes tbl_Dishes { get; set; }
        public virtual tbl_OrderDetails tbl_OrderDetails { get; set; }
    }
}
