//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Dishes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Dishes()
        {
            this.tbl_Cart = new HashSet<tbl_Cart>();
            this.tbl_OrderedFoodDetails = new HashSet<tbl_OrderedFoodDetails>();
        }
    
        public int DishId { get; set; }
        public string DishName { get; set; }
        public decimal DishPrice { get; set; }
        public string DishImage { get; set; }
        public string DishDesc { get; set; }
        public string VegOrNonveg { get; set; }
        public int Dish_fk_Rest { get; set; }
        public int Dish_fk_Cat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Cart> tbl_Cart { get; set; }
        public virtual tbl_Category tbl_Category { get; set; }
        public virtual tbl_Restaurant tbl_Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OrderedFoodDetails> tbl_OrderedFoodDetails { get; set; }
    }
}
