//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ContactUs
    {
        public int ContId { get; set; }
        public string ContName { get; set; }
        public string ContEmail { get; set; }
        public string ContMsg { get; set; }
    }
}
