//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Addresses
    {
        public int AddId { get; set; }
        public string DoorOrFlatNo { get; set; }
        public string LandMark { get; set; }
        public Nullable<int> AddressType { get; set; }
        public string PinCode { get; set; }
        public Nullable<int> Add_fk_CusId { get; set; }
    
        public virtual tbl_Customer tbl_Customer { get; set; }
        public virtual tbl_AddressType tbl_AddressType { get; set; }
    }
}
