//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DeliveryStaffs
    {
        public int StaffId { get; set; }
        public string StaffName { get; set; }
        public string StaffPhone { get; set; }
        public string StaffEmail { get; set; }
        public Nullable<System.DateTime> StaffDob { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string Gender { get; set; }
        public string VehicleNo { get; set; }
        public string VehicleType { get; set; }
        public string DrivingLicense { get; set; }
        public string AdhaarNo { get; set; }
        public string StaffAccStatus { get; set; }
        public string Isfree { get; set; }
    }
}
