//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OrderDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_OrderDetails()
        {
            this.tbl_OrderedFoodDetails = new HashSet<tbl_OrderedFoodDetails>();
        }
    
        public int OrderId { get; set; }
        public Nullable<int> Order_fk_CusId { get; set; }
        public Nullable<int> Order_fk_AddId { get; set; }
        public Nullable<int> Order_fk_RestId { get; set; }
        public Nullable<int> Order_fk_StaffId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> Orderdate { get; set; }
        public string PaymentMode { get; set; }
        public string IsPaid { get; set; }
        public string IsDelivered { get; set; }
        public string IsOrderConfirmed { get; set; }
        public string OrderOtp { get; set; }
    
        public virtual tbl_Addresses tbl_Addresses { get; set; }
        public virtual tbl_Customer tbl_Customer { get; set; }
        public virtual tbl_DeliveryStaffs tbl_DeliveryStaffs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OrderedFoodDetails> tbl_OrderedFoodDetails { get; set; }
        public virtual tbl_Restaurant tbl_Restaurant { get; set; }
    }
}
