//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ResBankAcc
    {
        public int id { get; set; }
        public Nullable<int> Rest_fk_BankName { get; set; }
        public string Branch { get; set; }
        public string AccNumber { get; set; }
        public string IfscCode { get; set; }
        public Nullable<int> bank_fk_RestId { get; set; }
    
        public virtual tbl_BankNames tbl_BankNames { get; set; }
        public virtual tbl_Restaurant tbl_Restaurant { get; set; }
    }
}
