//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Restaurant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Restaurant()
        {
            this.tbl_Cart = new HashSet<tbl_Cart>();
            this.tbl_FavRestaurants = new HashSet<tbl_FavRestaurants>();
            this.tbl_Dishes = new HashSet<tbl_Dishes>();
            this.tbl_OrderDetails = new HashSet<tbl_OrderDetails>();
            this.tbl_ReviewAndRating = new HashSet<tbl_ReviewAndRating>();
            this.tbl_ResBankAcc = new HashSet<tbl_ResBankAcc>();
        }
    
        public int RestId { get; set; }
        public string RestName { get; set; }
        public string RestPhone { get; set; }
        public string RestEmail { get; set; }
        public string RestPincode { get; set; }
        public string RestImage { get; set; }
        public string RestCountry { get; set; }
        public string RestState { get; set; }
        public string RestDistrict { get; set; }
        public string RestPassword { get; set; }
        public string RestStatus { get; set; }
        public string RestTradeLicense { get; set; }
        public Nullable<int> RestRole { get; set; }
        public string RestArea { get; set; }
        public string IsValid { get; set; }
        public Nullable<int> Rest_fk_Offer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Cart> tbl_Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FavRestaurants> tbl_FavRestaurants { get; set; }
        public virtual tbl_Role tbl_Role { get; set; }
        public virtual tbl_Offers tbl_Offers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Dishes> tbl_Dishes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OrderDetails> tbl_OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ReviewAndRating> tbl_ReviewAndRating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ResBankAcc> tbl_ResBankAcc { get; set; }
    }
}
